package hcmut.edu.vn.tutor_support_system.service;

import hcmut.edu.vn.tutor_support_system.dto.AnalyticsReportDto;
import hcmut.edu.vn.tutor_support_system.entity.StaffRole;
import hcmut.edu.vn.tutor_support_system.exception.ValidationException;
import hcmut.edu.vn.tutor_support_system.repository.*;
import hcmut.edu.vn.tutor_support_system.util.ValidationUtil;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@RequiredArgsConstructor
public class AnalyticsService {

  private final SessionRepository sessionRepository;
  private final FeedbackRepository feedbackRepository;
  private final MaterialRepository materialRepository;
  private final EvaluationRepository evaluationRepository;
  private final TutorRepository tutorRepository;
  private final StudentRepository studentRepository;

  @Transactional(readOnly = true)
  public AnalyticsReportDto generateTutorPerformanceReport(String generatedBy) {
    ValidationUtil.validateNotEmpty(generatedBy, "Generated by");

    Map<String, Object> data = new HashMap<>();

    Long totalTutors = tutorRepository.count();
    Long totalSessions = sessionRepository.count();
    Double avgRating =
        feedbackRepository.findAll().stream().mapToInt(f -> f.getRating()).average().orElse(0.0);

    data.put("totalTutors", totalTutors);
    data.put("totalSessions", totalSessions);
    data.put("averageRating", avgRating);
    data.put("totalFeedbackCount", feedbackRepository.count());

    return AnalyticsReportDto.builder()
        .reportType("TUTOR_PERFORMANCE")
        .generatedAt(LocalDateTime.now())
        .generatedBy(generatedBy)
        .data(data)
        .summary(
            String.format(
                "Tutor Performance Report: %d tutors, %d sessions, %.2f avg rating",
                totalTutors, totalSessions, avgRating))
        .build();
  }

  @Transactional(readOnly = true)
  public AnalyticsReportDto generateStudentEngagementReport(String generatedBy) {
    ValidationUtil.validateNotEmpty(generatedBy, "Generated by");

    Map<String, Object> data = new HashMap<>();

    Long totalStudents = studentRepository.count();
    Long totalSessions = sessionRepository.count();
    Long totalFeedback = feedbackRepository.count();

    data.put("totalStudents", totalStudents);
    data.put("totalSessions", totalSessions);
    data.put("totalFeedback", totalFeedback);
    data.put(
        "feedbackRate", totalSessions > 0 ? (double) totalFeedback / totalSessions * 100 : 0.0);

    return AnalyticsReportDto.builder()
        .reportType("STUDENT_ENGAGEMENT")
        .generatedAt(LocalDateTime.now())
        .generatedBy(generatedBy)
        .data(data)
        .summary(
            String.format(
                "Student Engagement Report: %d students, %d sessions, %.1f%% feedback rate",
                totalStudents,
                totalSessions,
                totalSessions > 0 ? (double) totalFeedback / totalSessions * 100 : 0.0))
        .build();
  }

  @Transactional(readOnly = true)
  public AnalyticsReportDto generateMaterialUsageReport(String generatedBy) {
    ValidationUtil.validateNotEmpty(generatedBy, "Generated by");

    Map<String, Object> data = new HashMap<>();

    Long totalMaterials = materialRepository.count();
    Long totalSessions = sessionRepository.count();

    data.put("totalMaterials", totalMaterials);
    data.put("totalSessions", totalSessions);
    data.put(
        "materialsPerSession", totalSessions > 0 ? (double) totalMaterials / totalSessions : 0.0);

    return AnalyticsReportDto.builder()
        .reportType("MATERIAL_USAGE")
        .generatedAt(LocalDateTime.now())
        .generatedBy(generatedBy)
        .data(data)
        .summary(
            String.format(
                "Material Usage Report: %d materials, %.2f materials per session",
                totalMaterials, totalSessions > 0 ? (double) totalMaterials / totalSessions : 0.0))
        .build();
  }

  @Transactional(readOnly = true)
  public AnalyticsReportDto generateReportByStaffRole(StaffRole staffRole, String generatedBy) {
    ValidationUtil.validateNotNull(staffRole, "Staff role");
    ValidationUtil.validateNotEmpty(generatedBy, "Generated by");

    switch (staffRole) {
      case ADS:
        return generateTutorPerformanceReport(generatedBy);
      case OAA:
        return generateStudentEngagementReport(generatedBy);
      case OSA:
        return generateMaterialUsageReport(generatedBy);
      default:
        throw new ValidationException("Invalid staff role for analytics: " + staffRole);
    }
  }

  @Transactional(readOnly = true)
  public AnalyticsReportDto generateComprehensiveReport(String generatedBy) {
    ValidationUtil.validateNotEmpty(generatedBy, "Generated by");

    Map<String, Object> data = new HashMap<>();

    data.put("totalTutors", tutorRepository.count());
    data.put("totalStudents", studentRepository.count());
    data.put("totalSessions", sessionRepository.count());
    data.put("totalFeedback", feedbackRepository.count());
    data.put("totalMaterials", materialRepository.count());
    data.put("totalEvaluations", evaluationRepository.count());

    Double avgRating =
        feedbackRepository.findAll().stream().mapToInt(f -> f.getRating()).average().orElse(0.0);
    data.put("averageRating", avgRating);

    return AnalyticsReportDto.builder()
        .reportType("COMPREHENSIVE")
        .generatedAt(LocalDateTime.now())
        .generatedBy(generatedBy)
        .data(data)
        .summary("Comprehensive analytics report covering all system metrics")
        .build();
  }
}
